---
title: "HW08"
author: "Jonathan Stuart"
date: "4/17/2018"
output: pdf_document
---

##Ch 13
###Problem 2

```{r}
chinese <- c(55, 33, 70, 49)
chinese_sum <- sum(chinese)
jewish <- c(141, 145, 139, 161)
jewish_sum <- sum(jewish)

e11 <- chinese_sum*(chinese[1]+jewish[1])/sum(chinese_sum, jewish_sum)
e21 <- chinese_sum*(chinese[2]+jewish[2])/sum(chinese_sum, jewish_sum)
e31 <- chinese_sum*(chinese[3]+jewish[3])/sum(chinese_sum, jewish_sum)
e41 <- chinese_sum*(chinese[4]+jewish[4])/sum(chinese_sum, jewish_sum)
chinese_expectation <- c(e11, e21, e31, e41)

e12 <- jewish_sum*(chinese[1]+jewish[1])/sum(chinese_sum, jewish_sum)
e22 <- jewish_sum*(chinese[2]+jewish[2])/sum(chinese_sum, jewish_sum)
e32 <- jewish_sum*(chinese[3]+jewish[3])/sum(chinese_sum, jewish_sum)
e42 <- jewish_sum*(chinese[4]+jewish[4])/sum(chinese_sum, jewish_sum)
jewish_expectation <- c(e12, e22, e32, e42)

test_statistic <- sum((chinese - chinese_expectation)^2 / chinese_expectation) + sum((jewish - jewish_expectation)^2 / jewish_expectation)
```

###Problem 6
```{r}
female <- c(51, 14, 38)
female_sum <- sum(female)
male <- c(38, 16, 46)
male_sum <- sum(male)

e11 <- female_sum*(female[1]+male[1])/sum(female_sum, male_sum)
e21 <- female_sum*(female[2]+male[2])/sum(female_sum, male_sum)
e31 <- female_sum*(female[3]+male[3])/sum(female_sum, male_sum)
female_expectation <- c(e11, e21, e31)

e12 <- male_sum*(female[1]+male[1])/sum(female_sum, male_sum)
e22 <- male_sum*(female[2]+male[2])/sum(female_sum, male_sum)
e32 <- male_sum*(female[3]+male[3])/sum(female_sum, male_sum)
male_expectation <- c(e12, e22, e32)

test_statistic <- sum((female - female_expectation)^2 / female_expectation) + sum((male - male_expectation)^2 / male_expectation)
```


```{r}
#p value of test statistic
1- pchisq(.0277, 1)
```

###Problem 14
(b)
```{r}
#hypothesis 1.1.
under_45 <- c(71, 305)
under_45_sum <- sum(under_45)
over_45 <- c(217, 652)
over_45_sum <- sum(over_45)

e11 <- under_45_sum*(under_45[1]+over_45[1])/sum(under_45_sum, over_45_sum)
e21 <- under_45_sum*(under_45[2]+over_45[2])/sum(under_45_sum, over_45_sum)
under_45_expectation <- c(e11, e21)

e12 <- over_45_sum*(under_45[1]+over_45[1])/sum(under_45_sum, over_45_sum)
e22 <- over_45_sum*(under_45[2]+over_45[2])/sum(under_45_sum, over_45_sum)
over_45_expectation <- c(e12, e22)

test_statistic <- sum((under_45 - under_45_expectation)^2 / under_45_expectation) + sum((over_45 - over_45_expectation)^2 / over_45_expectation)
```
```{r}
#hypothesis 1.2.
under_45 <- c(305, 869)
under_45_sum <- sum(under_45)
over_45 <- c(180, 259)
over_45_sum <- sum(over_45)

e11 <- under_45_sum*(under_45[1]+over_45[1])/sum(under_45_sum, over_45_sum)
e21 <- under_45_sum*(under_45[2]+over_45[2])/sum(under_45_sum, over_45_sum)
under_45_expectation <- c(e11, e21)

e12 <- over_45_sum*(under_45[1]+over_45[1])/sum(under_45_sum, over_45_sum)
e22 <- over_45_sum*(under_45[2]+over_45[2])/sum(under_45_sum, over_45_sum)
over_45_expectation <- c(e12, e22)

test_statistic <- sum((under_45 - under_45_expectation)^2 / under_45_expectation) + sum((over_45 - over_45_expectation)^2 / over_45_expectation)
````
```{r}
#hypothesis 2.1.
some_hs <- c(305, 869)
some_hs_sum <- sum(some_hs)
no_hs <- c(71, 305)
no_hs_sum <- sum(no_hs)

e11 <- some_hs_sum*(some_hs[1]+no_hs[1])/sum(some_hs_sum, no_hs_sum)
e21 <- some_hs_sum*(some_hs[2]+no_hs[2])/sum(some_hs_sum, no_hs_sum)
some_hs_expectation <- c(e11, e21)

e12 <- no_hs_sum*(some_hs[1]+no_hs[1])/sum(some_hs_sum, no_hs_sum)
e22 <- no_hs_sum*(some_hs[2]+no_hs[2])/sum(some_hs_sum, no_hs_sum)
no_hs_expectation <- c(e12, e22)

test_statistic <- sum((some_hs - some_hs_expectation)^2 / some_hs_expectation) + sum((no_hs - no_hs_expectation)^2 / no_hs_expectation)
````
```{r}
#hypothesis 2.2.
some_hs <- c(180, 259)
some_hs_sum <- sum(some_hs)
no_hs <- c(217, 652)
no_hs_sum <- sum(no_hs)

e11 <- some_hs_sum*(some_hs[1]+no_hs[1])/sum(some_hs_sum, no_hs_sum)
e21 <- some_hs_sum*(some_hs[2]+no_hs[2])/sum(some_hs_sum, no_hs_sum)
some_hs_expectation <- c(e11, e21)

e12 <- no_hs_sum*(some_hs[1]+no_hs[1])/sum(some_hs_sum, no_hs_sum)
e22 <- no_hs_sum*(some_hs[2]+no_hs[2])/sum(some_hs_sum, no_hs_sum)
no_hs_expectation <- c(e12, e22)

test_statistic <- sum((some_hs - some_hs_expectation)^2 / some_hs_expectation) + sum((no_hs - no_hs_expectation)^2 / no_hs_expectation)
```

###Problem 16
```{r}
cautious <- c(79, 10, 10)
cautious_sum <- sum(cautious)
neutral <- c(58, 8, 34)
neutral_sum <- sum(neutral)
explorer <- c(49, 9, 42)
explorer_sum <- sum(explorer)
```
```{r}
e11 <- cautious_sum*(cautious[1]+neutral[1]+explorer[1])/sum(cautious_sum, neutral_sum, explorer_sum)
e21 <- cautious_sum*(cautious[2]+neutral[2]+explorer[2])/sum(cautious_sum, neutral_sum, explorer_sum)
e31 <- cautious_sum*(cautious[3]+neutral[3]+explorer[3])/sum(cautious_sum, neutral_sum, explorer_sum)
cautious_expectation <- c(e11, e21, e31)

e12 <- neutral_sum*(cautious[1]+neutral[1]+explorer[1])/sum(cautious_sum, neutral_sum, explorer_sum)
e22 <- neutral_sum*(cautious[2]+neutral[2]+explorer[2])/sum(cautious_sum, neutral_sum, explorer_sum)
e32 <- neutral_sum*(cautious[3]+neutral[3]+explorer[3])/sum(cautious_sum, neutral_sum, explorer_sum)
neutral_expectation <- c(e12, e22, e32)

e13 <- explorer_sum*(cautious[1]+neutral[1]+explorer[1])/sum(cautious_sum, neutral_sum, explorer_sum)
e23 <- explorer_sum*(cautious[2]+neutral[2]+explorer[2])/sum(cautious_sum, neutral_sum, explorer_sum)
e33 <- explorer_sum*(cautious[3]+neutral[3]+explorer[3])/sum(cautious_sum, neutral_sum, explorer_sum)
explorer_expectation <- c(e13, e23, e33)

test_statistic <- sum((cautious - cautious_expectation)^2 / cautious_expectation) + sum((neutral - neutral_expectation)^2 / neutral_expectation)+ sum((explorer - explorer_expectation)^2 / explorer_expectation)
```

##Ch 14
###Problem 2
```{r}
#creating vectors and calculating averages
x <- c(.34, 1.38, -.65, .68, 1.4, -.88, -.3, -1.18, .5, -1.75)
x_bar <- mean(x)
y <- c(.27, 1.34, -.53, .35, 1.28, -.98, -.72, -.81, .64, -1.59)
y_bar <- mean(y)

#fitting lines using least squares
beta_hat_1 <- sum((x - x_bar) * (y - y_bar)) / sum((x - x_bar)^2)
beta_hat_0 <- y_bar - (beta_hat_1 * x_bar)

beta_hat_2 <- sum((x - x_bar) * (y - y_bar)) / sum((y - y_bar)^2)
beta_hat_3 <- x_bar - (beta_hat_2 * y_bar)

#plotting points
plot(x, y, main = "Plot of y versus x", ylab = "y-values", xlab = "x-values")
abline(beta_hat_0, beta_hat_1, col = "red")
abline(beta_hat_3, beta_hat_2, col = "blue")
text(1.1, .45, labels = " from y = a + bx", col = "red")
text(.4, .95, labels = " from x = c + dy", col = "blue")
```

